# Generated by Django 5.0.4 on 2024-07-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_brgy_item_citizenship_item_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='brgy',
            new_name='blood_type',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='city',
            new_name='father_last_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='employment_status',
            new_name='graduate_studies',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='father_surname',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='mother_surname',
            new_name='mother_last_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='street',
            new_name='religion',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='subd',
            new_name='vocational',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='vocational_tradecourse',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='item',
            name='father_name_ext',
        ),
        migrations.RemoveField(
            model_name='item',
            name='house_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mother_name_ext',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name_ext',
        ),
        migrations.RemoveField(
            model_name='item',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='item',
            name='birthday',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='zip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='citizenship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='civil_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sex',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
